/* This file was generated by SableCC (http://www.sablecc.org/). */

package gr.uoa.di.std08169.compilers.sablecc.node;

import gr.uoa.di.std08169.compilers.sablecc.analysis.*;

@SuppressWarnings("nls")
public final class AEmptyExp2Exp2 extends PExp2
{

    public AEmptyExp2Exp2()
    {
        // Constructor
    }

    @Override
    public Object clone()
    {
        return new AEmptyExp2Exp2();
    }

    public void apply(Switch sw)
    {
        ((Analysis) sw).caseAEmptyExp2Exp2(this);
    }

    @Override
    public String toString()
    {
        return "";
    }

    @Override
    void removeChild(@SuppressWarnings("unused") Node child)
    {
        // Remove child
        throw new RuntimeException("Not a child.");
    }

    @Override
    void replaceChild(@SuppressWarnings("unused") Node oldChild, @SuppressWarnings("unused") Node newChild)
    {
        // Replace child
        throw new RuntimeException("Not a child.");
    }
}
