/* This file was generated by SableCC (http://www.sablecc.org/). */

package gr.uoa.di.std08169.compilers.sablecc.parser;

import gr.uoa.di.std08169.compilers.sablecc.lexer.*;
import gr.uoa.di.std08169.compilers.sablecc.node.*;
import gr.uoa.di.std08169.compilers.sablecc.analysis.*;
import java.util.*;

import java.io.DataInputStream;
import java.io.BufferedInputStream;
import java.io.IOException;

@SuppressWarnings("nls")
public class Parser
{
    public final Analysis ignoredTokens = new AnalysisAdapter();

    protected ArrayList nodeList;

    private final Lexer lexer;
    private final ListIterator stack = new LinkedList().listIterator();
    private int last_pos;
    private int last_line;
    private Token last_token;
    private final TokenIndex converter = new TokenIndex();
    private final int[] action = new int[2];

    private final static int SHIFT = 0;
    private final static int REDUCE = 1;
    private final static int ACCEPT = 2;
    private final static int ERROR = 3;

    public Parser(@SuppressWarnings("hiding") Lexer lexer)
    {
        this.lexer = lexer;
    }

    protected void filter() throws ParserException, LexerException, IOException
    {
        // Empty body
    }

    private void push(int numstate, ArrayList listNode, boolean hidden) throws ParserException, LexerException, IOException
    {
        this.nodeList = listNode;

        if(!hidden)
        {
            filter();
        }

        if(!this.stack.hasNext())
        {
            this.stack.add(new State(numstate, this.nodeList));
            return;
        }

        State s = (State) this.stack.next();
        s.state = numstate;
        s.nodes = this.nodeList;
    }

    private int goTo(int index)
    {
        int state = state();
        int low = 1;
        int high = gotoTable[index].length - 1;
        int value = gotoTable[index][0][1];

        while(low <= high)
        {
            int middle = (low + high) / 2;

            if(state < gotoTable[index][middle][0])
            {
                high = middle - 1;
            }
            else if(state > gotoTable[index][middle][0])
            {
                low = middle + 1;
            }
            else
            {
                value = gotoTable[index][middle][1];
                break;
            }
        }

        return value;
    }

    private int state()
    {
        State s = (State) this.stack.previous();
        this.stack.next();
        return s.state;
    }

    private ArrayList pop()
    {
        return ((State) this.stack.previous()).nodes;
    }

    private int index(Switchable token)
    {
        this.converter.index = -1;
        token.apply(this.converter);
        return this.converter.index;
    }

    @SuppressWarnings("unchecked")
    public Start parse() throws ParserException, LexerException, IOException
    {
        push(0, null, true);
        List<Node> ign = null;
        while(true)
        {
            while(index(this.lexer.peek()) == -1)
            {
                if(ign == null)
                {
                    ign = new LinkedList<Node>();
                }

                ign.add(this.lexer.next());
            }

            if(ign != null)
            {
                this.ignoredTokens.setIn(this.lexer.peek(), ign);
                ign = null;
            }

            this.last_pos = this.lexer.peek().getPos();
            this.last_line = this.lexer.peek().getLine();
            this.last_token = this.lexer.peek();

            int index = index(this.lexer.peek());
            this.action[0] = Parser.actionTable[state()][0][1];
            this.action[1] = Parser.actionTable[state()][0][2];

            int low = 1;
            int high = Parser.actionTable[state()].length - 1;

            while(low <= high)
            {
                int middle = (low + high) / 2;

                if(index < Parser.actionTable[state()][middle][0])
                {
                    high = middle - 1;
                }
                else if(index > Parser.actionTable[state()][middle][0])
                {
                    low = middle + 1;
                }
                else
                {
                    this.action[0] = Parser.actionTable[state()][middle][1];
                    this.action[1] = Parser.actionTable[state()][middle][2];
                    break;
                }
            }

            switch(this.action[0])
            {
                case SHIFT:
		    {
		        ArrayList list = new ArrayList();
		        list.add(this.lexer.next());
                        push(this.action[1], list, false);
                    }
		    break;
                case REDUCE:
                    switch(this.action[1])
                    {
                    case 0: /* reduce AExpExp */
		    {
			ArrayList list = new0();
			push(goTo(0), list, false);
		    }
		    break;
                    case 1: /* reduce APlusExp2Exp2 */
		    {
			ArrayList list = new1();
			push(goTo(1), list, false);
		    }
		    break;
                    case 2: /* reduce AMinusExp2Exp2 */
		    {
			ArrayList list = new2();
			push(goTo(1), list, false);
		    }
		    break;
                    case 3: /* reduce AEmptyExp2Exp2 */
		    {
			ArrayList list = new3();
			push(goTo(1), list, false);
		    }
		    break;
                    case 4: /* reduce ATermTerm */
		    {
			ArrayList list = new4();
			push(goTo(2), list, false);
		    }
		    break;
                    case 5: /* reduce AMultTerm2Term2 */
		    {
			ArrayList list = new5();
			push(goTo(3), list, false);
		    }
		    break;
                    case 6: /* reduce ADivTerm2Term2 */
		    {
			ArrayList list = new6();
			push(goTo(3), list, false);
		    }
		    break;
                    case 7: /* reduce AEmptyTerm2Term2 */
		    {
			ArrayList list = new7();
			push(goTo(3), list, false);
		    }
		    break;
                    case 8: /* reduce ANumFactorFactor */
		    {
			ArrayList list = new8();
			push(goTo(4), list, false);
		    }
		    break;
                    case 9: /* reduce AExpFactorFactor */
		    {
			ArrayList list = new9();
			push(goTo(4), list, false);
		    }
		    break;
                    }
                    break;
                case ACCEPT:
                    {
                        EOF node2 = (EOF) this.lexer.next();
                        PExp node1 = (PExp) pop().get(0);
                        Start node = new Start(node1, node2);
                        return node;
                    }
                case ERROR:
                    throw new ParserException(this.last_token,
                        "[" + this.last_line + "," + this.last_pos + "] " +
                        Parser.errorMessages[Parser.errors[this.action[1]]]);
            }
        }
    }



    @SuppressWarnings("unchecked")
    ArrayList new0() /* reduce AExpExp */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp pexpNode1;
        {
            // Block
        PTerm ptermNode2;
        PExp2 pexp2Node3;
        ptermNode2 = (PTerm)nodeArrayList1.get(0);
        pexp2Node3 = (PExp2)nodeArrayList2.get(0);

        pexpNode1 = new AExpExp(ptermNode2, pexp2Node3);
        }
	nodeList.add(pexpNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new1() /* reduce APlusExp2Exp2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        TPlus tplusNode2;
        PTerm ptermNode3;
        PExp2 pexp2Node4;
        tplusNode2 = (TPlus)nodeArrayList1.get(0);
        ptermNode3 = (PTerm)nodeArrayList2.get(0);
        pexp2Node4 = (PExp2)nodeArrayList3.get(0);

        pexp2Node1 = new APlusExp2Exp2(tplusNode2, ptermNode3, pexp2Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new2() /* reduce AMinusExp2Exp2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PExp2 pexp2Node1;
        {
            // Block
        TMinus tminusNode2;
        PTerm ptermNode3;
        PExp2 pexp2Node4;
        tminusNode2 = (TMinus)nodeArrayList1.get(0);
        ptermNode3 = (PTerm)nodeArrayList2.get(0);
        pexp2Node4 = (PExp2)nodeArrayList3.get(0);

        pexp2Node1 = new AMinusExp2Exp2(tminusNode2, ptermNode3, pexp2Node4);
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new3() /* reduce AEmptyExp2Exp2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PExp2 pexp2Node1;
        {
            // Block

        pexp2Node1 = new AEmptyExp2Exp2();
        }
	nodeList.add(pexp2Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new4() /* reduce ATermTerm */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm ptermNode1;
        {
            // Block
        PFactor pfactorNode2;
        PTerm2 pterm2Node3;
        pfactorNode2 = (PFactor)nodeArrayList1.get(0);
        pterm2Node3 = (PTerm2)nodeArrayList2.get(0);

        ptermNode1 = new ATermTerm(pfactorNode2, pterm2Node3);
        }
	nodeList.add(ptermNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new5() /* reduce AMultTerm2Term2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm2 pterm2Node1;
        {
            // Block
        TMult tmultNode2;
        PFactor pfactorNode3;
        PTerm2 pterm2Node4;
        tmultNode2 = (TMult)nodeArrayList1.get(0);
        pfactorNode3 = (PFactor)nodeArrayList2.get(0);
        pterm2Node4 = (PTerm2)nodeArrayList3.get(0);

        pterm2Node1 = new AMultTerm2Term2(tmultNode2, pfactorNode3, pterm2Node4);
        }
	nodeList.add(pterm2Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new6() /* reduce ADivTerm2Term2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PTerm2 pterm2Node1;
        {
            // Block
        TDiv tdivNode2;
        PFactor pfactorNode3;
        PTerm2 pterm2Node4;
        tdivNode2 = (TDiv)nodeArrayList1.get(0);
        pfactorNode3 = (PFactor)nodeArrayList2.get(0);
        pterm2Node4 = (PTerm2)nodeArrayList3.get(0);

        pterm2Node1 = new ADivTerm2Term2(tdivNode2, pfactorNode3, pterm2Node4);
        }
	nodeList.add(pterm2Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new7() /* reduce AEmptyTerm2Term2 */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        PTerm2 pterm2Node1;
        {
            // Block

        pterm2Node1 = new AEmptyTerm2Term2();
        }
	nodeList.add(pterm2Node1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new8() /* reduce ANumFactorFactor */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        TNum tnumNode2;
        tnumNode2 = (TNum)nodeArrayList1.get(0);

        pfactorNode1 = new ANumFactorFactor(tnumNode2);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    @SuppressWarnings("unchecked")
    ArrayList new9() /* reduce AExpFactorFactor */
    {
        @SuppressWarnings("hiding") ArrayList nodeList = new ArrayList();

        @SuppressWarnings("unused") ArrayList nodeArrayList3 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList2 = pop();
        @SuppressWarnings("unused") ArrayList nodeArrayList1 = pop();
        PFactor pfactorNode1;
        {
            // Block
        TLeftParenthesis tleftparenthesisNode2;
        PExp pexpNode3;
        TRightParenthesis trightparenthesisNode4;
        tleftparenthesisNode2 = (TLeftParenthesis)nodeArrayList1.get(0);
        pexpNode3 = (PExp)nodeArrayList2.get(0);
        trightparenthesisNode4 = (TRightParenthesis)nodeArrayList3.get(0);

        pfactorNode1 = new AExpFactorFactor(tleftparenthesisNode2, pexpNode3, trightparenthesisNode4);
        }
	nodeList.add(pfactorNode1);
        return nodeList;
    }



    private static int[][][] actionTable;
/*      {
			{{-1, ERROR, 0}, {0, SHIFT, 1}, {5, SHIFT, 2}, },
			{{-1, REDUCE, 8}, },
			{{-1, ERROR, 2}, {0, SHIFT, 1}, {5, SHIFT, 2}, },
			{{-1, ERROR, 3}, {7, ACCEPT, -1}, },
			{{-1, REDUCE, 3}, {1, SHIFT, 7}, {2, SHIFT, 8}, },
			{{-1, REDUCE, 7}, {3, SHIFT, 10}, {4, SHIFT, 11}, },
			{{-1, ERROR, 6}, {6, SHIFT, 13}, },
			{{-1, ERROR, 7}, {0, SHIFT, 1}, {5, SHIFT, 2}, },
			{{-1, ERROR, 8}, {0, SHIFT, 1}, {5, SHIFT, 2}, },
			{{-1, REDUCE, 0}, },
			{{-1, ERROR, 10}, {0, SHIFT, 1}, {5, SHIFT, 2}, },
			{{-1, ERROR, 11}, {0, SHIFT, 1}, {5, SHIFT, 2}, },
			{{-1, REDUCE, 4}, },
			{{-1, REDUCE, 9}, },
			{{-1, REDUCE, 3}, {1, SHIFT, 7}, {2, SHIFT, 8}, },
			{{-1, REDUCE, 3}, {1, SHIFT, 7}, {2, SHIFT, 8}, },
			{{-1, REDUCE, 7}, {3, SHIFT, 10}, {4, SHIFT, 11}, },
			{{-1, REDUCE, 7}, {3, SHIFT, 10}, {4, SHIFT, 11}, },
			{{-1, REDUCE, 1}, },
			{{-1, REDUCE, 2}, },
			{{-1, REDUCE, 5}, },
			{{-1, REDUCE, 6}, },
        };*/
    private static int[][][] gotoTable;
/*      {
			{{-1, 3}, {2, 6}, },
			{{-1, 9}, {14, 18}, {15, 19}, },
			{{-1, 4}, {7, 14}, {8, 15}, },
			{{-1, 12}, {16, 20}, {17, 21}, },
			{{-1, 5}, {10, 16}, {11, 17}, },
        };*/
    private static String[] errorMessages;
/*      {
			"expecting: num, '('",
			"expecting: '+', '-', '*', '/', ')', EOF",
			"expecting: EOF",
			"expecting: '+', '-', ')', EOF",
			"expecting: ')'",
			"expecting: ')', EOF",
        };*/
    private static int[] errors;
/*      {
			0, 1, 0, 2, 3, 1, 4, 0, 0, 5, 0, 0, 3, 1, 3, 3, 1, 1, 5, 5, 3, 3, 
        };*/

    static 
    {
        try
        {
            DataInputStream s = new DataInputStream(
                new BufferedInputStream(
                Parser.class.getResourceAsStream("parser.dat")));

            // read actionTable
            int length = s.readInt();
            Parser.actionTable = new int[length][][];
            for(int i = 0; i < Parser.actionTable.length; i++)
            {
                length = s.readInt();
                Parser.actionTable[i] = new int[length][3];
                for(int j = 0; j < Parser.actionTable[i].length; j++)
                {
                for(int k = 0; k < 3; k++)
                {
                    Parser.actionTable[i][j][k] = s.readInt();
                }
                }
            }

            // read gotoTable
            length = s.readInt();
            gotoTable = new int[length][][];
            for(int i = 0; i < gotoTable.length; i++)
            {
                length = s.readInt();
                gotoTable[i] = new int[length][2];
                for(int j = 0; j < gotoTable[i].length; j++)
                {
                for(int k = 0; k < 2; k++)
                {
                    gotoTable[i][j][k] = s.readInt();
                }
                }
            }

            // read errorMessages
            length = s.readInt();
            errorMessages = new String[length];
            for(int i = 0; i < errorMessages.length; i++)
            {
                length = s.readInt();
                StringBuffer buffer = new StringBuffer();

                for(int j = 0; j < length; j++)
                {
                buffer.append(s.readChar());
                }
                errorMessages[i] = buffer.toString();
            }

            // read errors
            length = s.readInt();
            errors = new int[length];
            for(int i = 0; i < errors.length; i++)
            {
                errors[i] = s.readInt();
            }

            s.close();
        }
        catch(Exception e)
        {
            throw new RuntimeException("The file \"parser.dat\" is either missing or corrupted.");
        }
    }
}
