/* This file was generated by SableCC (http://www.sablecc.org/). */

package gr.uoa.di.std08169.compilers.sablecc.lexer;

@SuppressWarnings("serial")
public class LexerException extends Exception
{
    public LexerException(String message)
    {
        super(message);
    }
}
