/* This file was generated by SableCC (http://www.sablecc.org/). */

package gr.uoa.di.std08169.compilers.sablecc.analysis;

import gr.uoa.di.std08169.compilers.sablecc.node.*;

public interface Analysis extends Switch
{
    Object getIn(Node node);
    void setIn(Node node, Object o);
    Object getOut(Node node);
    void setOut(Node node, Object o);

    void caseStart(Start node);
    void caseAExpExp(AExpExp node);
    void caseAPlusExp2Exp2(APlusExp2Exp2 node);
    void caseAMinusExp2Exp2(AMinusExp2Exp2 node);
    void caseAEmptyExp2Exp2(AEmptyExp2Exp2 node);
    void caseATermTerm(ATermTerm node);
    void caseAMultTerm2Term2(AMultTerm2Term2 node);
    void caseADivTerm2Term2(ADivTerm2Term2 node);
    void caseAEmptyTerm2Term2(AEmptyTerm2Term2 node);
    void caseANumFactorFactor(ANumFactorFactor node);
    void caseAExpFactorFactor(AExpFactorFactor node);

    void caseTNum(TNum node);
    void caseTPlus(TPlus node);
    void caseTMinus(TMinus node);
    void caseTMult(TMult node);
    void caseTDiv(TDiv node);
    void caseTLeftParenthesis(TLeftParenthesis node);
    void caseTRightParenthesis(TRightParenthesis node);
    void caseTWhitespace(TWhitespace node);
    void caseEOF(EOF node);
}
