//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package homework6.syntaxtree;

/**
 * Grammar production:
 * f0 -> "PASSARG"
 * f1 -> IntegerLiteral()
 * f2 -> Reg()
 */
public class PassArgStmt implements Node {
   public NodeToken f0;
   public IntegerLiteral f1;
   public Reg f2;

   public PassArgStmt(NodeToken n0, IntegerLiteral n1, Reg n2) {
      f0 = n0;
      f1 = n1;
      f2 = n2;
   }

   public PassArgStmt(IntegerLiteral n0, Reg n1) {
      f0 = new NodeToken("PASSARG");
      f1 = n0;
      f2 = n1;
   }

   public void accept(homework6.visitor.Visitor v) {
      v.visit(this);
   }
   public <R,A> R accept(homework6.visitor.GJVisitor<R,A> v, A argu) {
      return v.visit(this,argu);
   }
   public <R> R accept(homework6.visitor.GJNoArguVisitor<R> v) {
      return v.visit(this);
   }
   public <A> void accept(homework6.visitor.GJVoidVisitor<A> v, A argu) {
      v.visit(this,argu);
   }
}

