//
// Generated by JTB 1.3.2 DIT@UoA patched
//

package homework4.syntaxtree;

/**
 * The interface which all syntax tree classes must implement.
 */
public interface Node extends java.io.Serializable {
   public void accept(homework4.visitor.Visitor v);
   public <R,A> R accept(homework4.visitor.GJVisitor<R,A> v, A argu);
   public <R> R accept(homework4.visitor.GJNoArguVisitor<R> v);
   public <A> void accept(homework4.visitor.GJVoidVisitor<A> v, A argu);
}

